import { TwoFactorProvider, TwoFactorSetupResult } from './TwoFactorProvider';
import * as speakeasy from 'speakeasy';
import * as qrcode from 'qrcode';

// Note: Install packages: npm install speakeasy qrcode @types/speakeasy @types/qrcode

export class TotpProvider implements TwoFactorProvider {

  /**
   * TOTP doesn't "send" codes - they're generated by the authenticator app
   * This method is not applicable for TOTP
   */
  async send(target: string, code?: string): Promise<boolean> {
    // TOTP doesn't send codes, so this always returns true
    return true;
  }

  /**
   * Verify TOTP code
   */
  async verify(secret: string, providedCode: string, expiresAt?: Date): Promise<boolean> {
    try {
      return speakeasy.totp.verify({
        secret,
        encoding: 'base32',
        token: providedCode,
        window: 2, // Allow 2 steps before/after for clock drift (30-second window each)
      });
    } catch (error) {
      console.error('TOTP verification failed:', error);
      return false;
    }
  }

  /**
   * Setup TOTP by generating secret and QR code
   */
  async setup(userEmail: string): Promise<TwoFactorSetupResult> {
    try {
      // Generate secret for the user
      const secret = speakeasy.generateSecret({
        name: `Drilling Operations - (${userEmail})`,  // Custom format
        issuer: 'Primefrontier',
        length: 32,
      });

      if (!secret.base32 || !secret.otpauth_url) {
        return {
          success: false,
          error: 'Failed to generate TOTP secret'
        };
      }

      // Generate QR code
      const qrCode = await this.generateQRCode(secret.otpauth_url);

      return {
        success: true,
        secret: secret.base32,
        qrCode: qrCode,
        message: 'Scan the QR code with your authenticator app and enter the 6-digit code to verify setup.'
      };
    } catch (error) {
      console.error('TOTP setup failed:', error);
      return {
        success: false,
        error: 'TOTP setup failed'
      };
    }
  }

  /**
   * Generate QR code for TOTP setup
   */
  private async generateQRCode(otpauthUrl: string): Promise<string> {
    try {
      return await qrcode.toDataURL(otpauthUrl);
    } catch (error) {
      throw new Error('Failed to generate QR code');
    }
  }

  /**
   * Generate a new TOTP secret (used during setup)
   */
  static generateSecret(userEmail: string): { secret: string; otpauthUrl: string } {
    const secret = speakeasy.generateSecret({
      name: userEmail,
      issuer: 'Primefrontier',
      length: 32,
    });

    return {
      secret: secret.base32!,
      otpauthUrl: secret.otpauth_url!,
    };
  }

  /**
   * Verify a TOTP token (static method for convenience)
   */
  static verifyToken(secret: string, token: string): boolean {
    return speakeasy.totp.verify({
      secret,
      encoding: 'base32',
      token,
      window: 2,
    });
  }
}